import { track } from '../tracker'

export type ClickedEvent =
  | 'button'
  | 'link'
  | 'footer_link'
  | 'external_link'
  | 'share'
  | 'share_completed'
  | 'theme'
  | 'navigation'
  | 'command_palette'
  | 'command_palette_command'
  | 'form_submit'
  | 'form_field'
  | 'search'
  | 'search_refine'
  | 'search_result'
  | 'search_filter'
  | 'search_clear'
  | 'quick_view'
  | 'quick_view_download'
  | 'election_compare'
  | 'election_year'
  | 'prediction_highlight'
  | 'prediction_highlight_cleared'
  | 'prediction_view_mode'
  | 'prediction_view_mode_changed'
  | 'prediction_predictor'
  | 'prediction_predictor_changed'
  | 'prediction_year_changed'
  | 'prediction_district_filter_changed'
  | 'prediction_search_cleared'
  | 'prediction_search_result_clicked'
  | 'prediction_mobile_tab_changed'
  | 'watchlist_seat'
  | 'election_results_map'
  | 'election_results_party_filter'
  | 'election_results_seat_click'

export function trackClicked(
  properties: { name: ClickedEvent; page_name: string } & Record<string, unknown>,
) {
  track('clicked', properties)
}
